/**
 * Region: sprite.
 *
 * One piece of the browser bundle. `tools/build-bundle.mjs` concatenates the
 * regions in order; `lib/client.js` is generated output and must never be
 * edited by hand. `tests/bundle.test.mjs` rebuilds it and fails on drift.
 */

export default "    /* ------------------------------------------------------------------ *\n     * Sprite rendering\n     * ------------------------------------------------------------------ */\n\n    /** Whether motion is currently allowed for this companion. */\n    function motionAllowed(prefs, systemReducedMotion) {\n      if (prefs.motion === 'off') return false;\n      if (prefs.motion === 'on') return true;\n      return !systemReducedMotion;\n    }\n\n    /**\n     * Advances an animation frame index on a timer.\n     *\n     * A timer rather than requestAnimationFrame: sprite animation runs at 4-12\n     * frames per second, so a per-frame callback would wake the compositor for\n     * nothing. The ticker stops outright when the sage is asleep or the tab is\n     * hidden, so an idle companion costs nothing.\n     */\n    function useFrameTicker(options) {\n      var fps = options.fps;\n      var loop = options.loop !== false;\n      var playing = options.playing !== false;\n      var count = Math.max(1, options.count || 1);\n      var key = options.key;\n      var [frame, setFrame] = React.useState(0);\n\n      // A new animation always starts from its first frame.\n      React.useEffect(\n        function () {\n          setFrame(0);\n        },\n        [key]\n      );\n\n      React.useEffect(\n        function () {\n          if (!playing || count <= 1 || !(fps > 0)) return undefined;\n          var timer = globalThis.setInterval(function () {\n            if (document.hidden) return;\n            setFrame(function (previous) {\n              var next = previous + 1;\n              if (next < count) return next;\n              return loop ? 0 : count - 1;\n            });\n          }, Math.max(60, Math.round(1000 / fps)));\n          return function () {\n            globalThis.clearInterval(timer);\n          };\n        },\n        [playing, count, fps, loop, key]\n      );\n\n      return frame;\n    }\n\n    /**\n     * A small still of the resting pose, used by the tucked-away restore button.\n     * Built from the same index so it cannot drift from the character.\n     */\n    function Thumbnail(props) {\n      var scale = props.scale;\n      var spec = spriteSpec({ state: 'resting', frame: 0, scale: scale });\n      return h('div', {\n        className: 'infj-sprite',\n        'aria-hidden': 'true',\n        style: {\n          backgroundImage: 'url(\"' + SHEET_URI + '\")',\n          backgroundSize: spec.backgroundSize,\n          backgroundPosition: spec.backgroundPosition,\n          width: spec.width + 'px',\n          height: spec.height + 'px'\n        }\n      });\n    }\n\n";
