#!/usr/bin/env node
/**
 * Builds a self-contained `preview.html` from the packaged assets.
 *
 * The preview is a development and documentation aid: it opens directly from
 * disk with no server, no DSH connection, and no model call. It renders the same
 * SVGs the plugin ships, under the same animation rules, so the six poses can be
 * reviewed without launching the app.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const client = readFileSync(join(root, 'lib', 'client.js'), 'utf8');

/**
 * Pulls the runtime stylesheet out of the bundle so the preview cannot drift
 * from what the plugin actually injects.
 */
function extractCss() {
  const start = client.indexOf('var CSS = [');
  const end = client.indexOf("].join('');", start);
  if (start < 0 || end < 0) throw new Error('could not locate the CSS block in lib/client.js');
  const body = client.slice(start + 'var CSS = ['.length, end);
  const parts = [...body.matchAll(/'((?:[^'\\]|\\.)*)'/g)].map((match) =>
    match[1].replace(/\\'/g, "'").replace(/\\\\/g, '\\')
  );
  return parts.join('');
}

const POSES = [
  { state: 'resting', zh: '静观', en: 'Observing', note: 'Idle: nothing is running.' },
  { state: 'working', zh: '洞察', en: 'Insight', note: 'At least one session is working.' },
  { state: 'waiting', zh: '共情', en: 'Empathy', note: 'A session is waiting on your answer.' },
  { state: 'celebrating', zh: '笃定', en: 'Resolve', note: 'A watched turn just finished.' },
  { state: 'sleeping', zh: '充电', en: 'Recharging', note: 'Quiet past the nap delay.' },
  { state: 'error', zh: '受挫', en: 'Setback', note: 'A turn ended in an error.' }
];

const css = extractCss();

const cards = POSES.map((pose) => {
  const svg = readFileSync(join(root, 'assets', `${pose.state}.svg`), 'utf8').trim();
  return `      <figure class="card">
        <div class="stage infj-pet" data-state="${pose.state}" data-motion="on" data-palette="light">
          <div class="infj-wrap" style="position:static;width:200px;aspect-ratio:1/1">${svg}</div>
        </div>
        <figcaption>
          <strong>${pose.zh}</strong> · ${pose.en}
          <span>${pose.note}</span>
          <code>data-state="${pose.state}"</code>
        </figcaption>
      </figure>`;
}).join('\n');

const icon = readFileSync(join(root, 'assets', 'icon.svg'), 'utf8').trim();

const html = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>INFJ Sage — pose preview</title>
<style>
${css}
  body {
    margin: 0; padding: 32px;
    font: 14px/1.6 system-ui, -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
    background: #EAF3E5; color: #1F3320;
  }
  h1 { font-size: 22px; margin: 0 0 4px; }
  p.lead { margin: 0 0 28px; color: #4E6B4A; }
  .grid { display: flex; flex-wrap: wrap; gap: 20px; }
  .card {
    margin: 0; padding: 16px; width: 232px; border-radius: 18px;
    background: rgba(255,255,255,0.72); border: 1px solid rgba(80,120,60,0.18);
  }
  .stage { position: relative; display: flex; justify-content: center; }
  figcaption { margin-top: 10px; font-size: 12px; color: #3C5539; }
  figcaption strong { font-size: 13px; }
  figcaption span { display: block; color: #5C7358; margin: 2px 0 6px; }
  figcaption code { font-size: 11px; color: #3E8F6B; }
  .icon-row { display: flex; align-items: center; gap: 14px; margin-top: 32px; }
  .icon-row svg { width: 64px; height: 64px; border-radius: 14px; }
  footer { margin-top: 28px; color: #5C7358; font-size: 12px; }
</style>
</head>
<body>
  <h1>INFJ Sage — 姿势预览 / pose preview</h1>
  <p class="lead">Six character states, each expressing one INFJ trait. Animations follow the system reduce-motion setting.</p>
  <div class="grid">
${cards}
  </div>
  <div class="icon-row">
    ${icon}
    <div><strong>Plugin icon</strong><br><span>head-only crop used by the plugin manager</span></div>
  </div>
  <footer>Offline preview generated by tools/build-preview.mjs — no DSH connection, no model calls.</footer>
</body>
</html>
`;

writeFileSync(join(root, 'preview.html'), html);
console.log('wrote preview.html (' + html.length + ' bytes)');
